[package]
name = "cheat_menu_re3"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "cheat_menu_re3"

[dependencies]
hudhook = { version = "0.3.0", features = ["simplelog"]}
imgui = "0.8.2"
pdb = "0.8.0"
toy-arms = {version = "0.9.4", features = ["internal"]}